#!/bin/bash
sudo dpkg -l |grep ^rc|awk '{print $2}' |sudo xargs dpkg -P > /dev/null 2>&1 > /dev/null
result=$(echo $?)
if [ $result = 0 ];
then
     echo "Package junks clean successful!"
else
     echo "Your system has already clean!"
fi
